### ISSUE TITLE
Add instructions for viewing access log to the setup guide

### ISSUE THREAD

**Issue by sebastianadams-music** [sebpiq/FreedomPortal#14]
Hi, I just managed to get this working on a gl-mt300n-v2 

(incidentally: the only change I needed to make in your code was to change paths from "PORTALKEY" to "sda1" as it didn't seem to read the name/label of the volume on the USB key)

I am trying to figure out how to access the visitor log and can't work it out from the code. I'm completely new to both OpenWRT and lihgttpd so please excuse me if this is actually obvious - but I wonder if it might be an important thing to add to the setup guide?

thanks so much for making this inspiring project available

**Comment by sebpiq** [comment]
Hi @sebastianadams-music !

In the [parameters](https://github.com/sebpiq/FreedomPortal/blob/master/parameters.lua.template) file, have you tried to set `log_visitors = false` to `true` ?

As the parameters file also suggests, you can specify the log folder to be on your USB stick so it doesn't get erased with each restart. 

Let me know how this goes, and whether you still think it should be better documented !

**Comment by sebastianadams-music** [comment]
ahh ok!! I totally missed that. Thanks a lot. No I think that's clear, I just didn't think to look there

**Comment by sebpiq** [comment]
Glad you figured it out ;)
