### ISSUE TITLE
FreedomPortal won't run

### ISSUE THREAD

**Issue by awardTour** [sebpiq/FreedomPortal#2]
Hello,

First of all, thanks for sharing and putting this together. I ran into this project while researching on ways to improve the captive portal experience -- specifically in linking out to Safari from iOS' CNA.

I was looking forward to trying this out but couldn't get it to run. I'm using a GL-inet mini router and ran through your entire read me without error. Connecting on both desktop and mobile produces no captive portal. Navigating to URLs in the browser behaves normally both with and without an internet connection.

I've pasted the contents of my log folder below. Did something change, or am I missing something?

Thanks again!

> lua: /root/FreedomPortal/freedomportal/openwrt.lua:24: attempt to index field '?' (a nil value)
stack traceback:
	/root/FreedomPortal/freedomportal/openwrt.lua:24: in function </root/FreedomPortal/freedomportal/openwrt.lua:21>
	/root/FreedomPortal/scripts/refresh_clients.lua:21: in main chunk
	[C]: ?
lua: /root/FreedomPortal/freedomportal/openwrt.lua:24: attempt to index field '?' (a nil value)
stack traceback:
	/root/FreedomPortal/freedomportal/openwrt.lua:24: in function </root/FreedomPortal/freedomportal/openwrt.lua:21>
	/root/FreedomPortal/freedomportal/clients/init.lua:24: in function 'get_clients'
	...FreedomPortal/freedomportal/clients/file_storage.lua:97: in function 'replace_all'
	/root/FreedomPortal/freedomportal/clients/init.lua:22: in function 'refresh'
	/root/FreedomPortal/scripts/refresh_clients.lua:23: in main chunk
	[C]: ?
lua: /root/FreedomPortal/freedomportal/openwrt.lua:24: attempt to index field '?' (a nil value)
stack traceback:
	/root/FreedomPortal/freedomportal/openwrt.lua:24: in function </root/FreedomPortal/freedomportal/openwrt.lua:21>
	/root/FreedomPortal/scripts/refresh_clients.lua:21: in main chunk
	[C]: ?
lua: /root/FreedomPortal/freedomportal/openwrt.lua:24: attempt to index field '?' (a nil value)
stack traceback:
	/root/FreedomPortal/freedomportal/openwrt.lua:24: in function </root/FreedomPortal/freedomportal/openwrt.lua:21>
	/root/FreedomPortal/freedomportal/clients/init.lua:24: in function 'get_clients'
	...FreedomPortal/freedomportal/clients/file_storage.lua:97: in function 'replace_all'
	/root/FreedomPortal/freedomportal/clients/init.lua:22: in function 'refresh'
	/root/FreedomPortal/scripts/refresh_clients.lua:23: in main chunk
	[C]: ?
warning : couldnt find an IP mapping for MAC address 8C:8E:F2:62:DB:48

**Comment by sebpiq** [comment]
Hi @awardTour! This is a pretty new project and there's definitely some bugs! 

Can you tell me which version of the firmware your GL-inet is using? You can see this info when you reset your router and go to the setup page at 192.168.8.1, there's a section in the menu for `firmware`. You might also be able to see it when you connect with SSH but I am not sure ...

It looks like there is a bug with the part of the code that detects connections. We could try to debug it, but my guess is you simply have a different version of the firmware than me, so I'd recommend updating it. It is very easy to do, just connect your router to Internet, and in the setup menu (192.168.8.1) in the firmware section there's a button "update firmware" which does everything automatically.

**Comment by awardTour** [comment]
Thanks @sebpiq, your assumption was right. I was on an older version of the firmware, upgrading fixed it.

Thanks again!

**Comment by awardTour** [comment]
Hi @sebpiq, one last question:

For consistency, what version of the firmware did you test this on? I'm currently on 2.25.

Thanks again!

**Comment by sebpiq** [comment]
Great! Glad you sorted it out :) I will add a note in the README to make this clear. I use the same version as you 2.25! Is everything working properly now?

**Comment by awardTour** [comment]
I think everything is working properly. The captive portal serves index.html from the `/www` folder when a client connects to the wireless network but only when the router is connected to the internet. 

I noticed that you've implemented iOS/Android handlers to display connected/unconnected pages. Is serving the `index.html` from `/www` the expected default behavior? If it is, what are the purposes for the Android and iOS pages?

**Comment by sebpiq** [comment]
Only when the router is connected to the Internet you said??? That is very strange ... It should work no matter whether the router has Internet or not. Can you double-check and tell me more about that?

> I noticed that you've implemented iOS/Android handlers to display connected/unconnected pages

With the default connection mode, the page normally opens in the CNA (pop-up) as soon as your device us connected to the Wi-Fi. Some features (like cookies) are not available in the CNA, so there is another mode which is a bit more complicated and allows to open a full browser window instead of the CNA. But I recommend to stick to this default mode.

**Comment by awardTour** [comment]
I've got it working offline now. Initially I added the line `list address '/#/192.168.8.1'` to the end of `/etc/config/dhcp` instead of under `config dnsmasq`. I felt like that was wrong but it wasn't clear from the readme.

Is switching to the other mode difficult? Ideally I'd like to click out of the CNA since my local app required more involved JS which doesn't run within the CNA browser.

Thanks again!

**Comment by sebpiq** [comment]
For that you need to modify the file [FreedomPortal/scripts/servers.lua](https://github.com/sebpiq/FreedomPortal/blob/master/scripts/server.lua#L15) replace : 

```config.set('client_handlers', { android = android.cna, ios = ios.cna })```

 with 

```config.set('client_handlers', { android = android.browser, ios = ios.browser })```

**Comment by sebpiq** [comment]
Ideally, you shouldn't have to modify some source file ... I created [an issue](https://github.com/sebpiq/FreedomPortal/issues/4), configuring should be easier :)
