### ISSUE TITLE
URL configuration

### ISSUE THREAD

**Issue by henll** [sebpiq/FreedomPortal#5]
Hello,

Very cool project !

I installed it on a OpenWRT router and tried it both on Android and iPhone, looks like everything is working fine but when I connect to the router WiFi, I'm always getting straight to my index page in the CNA. It does not go through Android or iOS connecting / connected pages, nor opens generic browser.

I am wondering if it could be a URL configuration problem; because I don't see the link between the URLs in lighttpd.conf and config.lua ?

In lighttpd.conf:
 alias.url = (
        "/_freedomportal" => "/root/FreedomPortal/pages/",

In config.lua:
    redirect_success = '/freedomportal_content',   
    captive_static_root_url = '/freedomportal_static',
    captive_dynamic_root_url = '/freedomportal',

Best regards,
henll

**Comment by sebpiq** [comment]
Hi @henll !
By default the system is configured to only open in CNA : https://github.com/sebpiq/FreedomPortal/blob/master/scripts/server.lua#L15

You can modify this line to fix this. However, my attempts to open a full browser on all devices where not very successful. It works on some versions of iOS, but some others not. So I decided to give up this mode and always open all in the CNA. I think this is the best option. The only drawback is some JavaScript/web features are not supported there. But a big majority is.

I am currently redoing completely the project to take this into account (only CNA from now on). The work is almost finished, but I haven't had time to publish it yet. You can find it there : https://github.com/sebpiq/FreedomPortal/tree/only-cna-mode

**Comment by sebpiq** [comment]
The new code is now merged to the project and instructions have been updated!
