### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by camenomato** [sebpiq/FreedomPortal#7]
Wont really call this an issue but more of a query from a complete noob...
(am fairly experienced in nodejs webpage routing building and stuff you can say but havent really done this so bear with please)

Im planning on/trying to use FreedomPortal on a private network server i have installed in my apartment complex and i wanted to know if i could

1) Use this to show a webpage that has login details on my mlab account(mlab is the online mongodb database thingie) and get approved and stuff from there
2) Have a set amount of data a user can view per time before he has to log in again(to stop people/guests with access from using torrents and downloading tons of movies/games in a single night and wasting bandwidth)
3) Display ads that connect online(if i allow certain domains, how am i supposed to set up for that?)

Thanks in advance!

**Comment by camenomato** [comment]
**idk how to contact you off github so i had to post the issue here :S

**Comment by sebpiq** [comment]
Hi @camenomato 
This is not really what the project is for. This goal of FreedomPortal is to implement a captive portal which consists of custom html pages and without access to Internet. To do that it only provides a configuration for lighttpd (a web server) and a few lua scripts to make some things easier, but implementing login, access control for different users etc ... is far away from my goals here, and from what you can do with the system at the moment. You should check-out some full-fledged open-source captive portals projects such as wifidog and others

**Comment by camenomato** [comment]
Uh alright thanks.

Just thought using this would provide me a more....customizable approach as compared to wifi dog and stuff.
Plus having it on the router directly would mean it doesnt need any extra hardware to operate/control its working.

Thanks anyway. Hope to see this project shaping well in the future!

**Comment by sebpiq** [comment]
Wifi dog runs on openwrt, so you can have it on your router!
Good luck with this!

**Comment by camenomato** [comment]
I believe its in python which i have no experience in :(
Plus I heard its development was discontinued a couple of years back(by the same work friend who told me about your project) 
Learning python to enable me to configure it according to my needs is kind of a bust eh?

**Comment by sebpiq** [comment]
Python is great tho ;)

**Comment by camenomato** [comment]
Its kind of in that subset of things I wanted to learn but i havent gotten to due to the lack of time and keep starting and then procrastinating learning further till i eventually drop it :X
